# تفعيل أندرويد إكس (إلزامي للمكتبات الحديثة)
android.useAndroidX=true

# إيقاف Jetifier لزيادة سرعة البناء
# بما أننا نستخدم مكتبات حديثة كلياً، لم نعد بحاجة لتحويل المكتبات القديمة، وهذا يوفر وقتاً كبيراً
android.enableJetifier=false

# تجاوز تحذيرات إصدار SDK (ضروري لأننا نستخدم SDK 35)
android.suppressUnsupportedCompileSdk=35

# تفعيل المعالجة المتوازية لزيادة سرعة الـ Build في أندرويد ستوديو
org.gradle.parallel=true

# تخصيص حجم الذاكرة (RAM) لعملية البناء لضمان استقرار KAPT و Room
# 4 جيجابايت هي القيمة المثالية لضمان عدم حدوث خطأ OutOfMemory
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# تفعيل التخزين المؤقت (Caching) لعمليات البناء السابقة
org.gradle.caching=true

# تحسين أداء لغة Kotlin أثناء المعالجة
kotlin.incremental=true
kotlin.code.style=official
