pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // فرض مركزية المستودعات (Strict Centralization) ومنع الموديولات من تجاوزها
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    
    repositories {
        google()
        mavenCentral()
        
        // ضروري لجلب المكتبات المستضافة على GitHub (مثل مكتبة Fetch)
        maven { 
            url 'https://jitpack.io' 
        }
    }
}

rootProject.name = "ABDULLAH STORE"

include ':app'
